package com.becomedigital.sdk.identity.becomedigitalsdk.utils;

import android.app.Activity;
import android.util.Log;

import com.becomedigital.sdk.identity.becomedigitalsdk.models.CountriesView;
import com.becomedigital.sdk.identity.becomedigitalsdk.models.Countries_DB;

import java.util.ArrayList;

public class LoadCountries {
    public static void loadCountries(final Activity activity) {
        CountriesView countriesView = new CountriesView ( );

        if (countriesView.isNullEntity (activity)) {

            ArrayList<Countries_DB> countriesList = new ArrayList<Countries_DB> ( );
            countriesList.add (new Countries_DB ("Afghanistan", "JAA", "afg", "af"));
            countriesList.add (new Countries_DB ("Albania", "TIA", "alb", "al"));
            countriesList.add (new Countries_DB ("Algeria", "ALG", "dza", "dz"));
            countriesList.add (new Countries_DB ("Andorra", "ALV", "and", "ad"));
            countriesList.add (new Countries_DB ("Angola", "BUG", "ago", "ao"));
            countriesList.add (new Countries_DB ("Anguilla", "AXA", "aia", "ai"));
            countriesList.add (new Countries_DB ("Antigua and Barbuda", "ANU", "atg", "ag"));
            countriesList.add (new Countries_DB ("Argentina", "BUE", "arg", "ar"));
            countriesList.add (new Countries_DB ("Armenia", "EVN", "arm", "am"));
            countriesList.add (new Countries_DB ("Aruba", "AUA", "abw", "aw"));
            countriesList.add (new Countries_DB ("Australia", "ADL", "aus", "au"));
            countriesList.add (new Countries_DB ("Austria", "GRZ", "aut", "at"));
            countriesList.add (new Countries_DB ("Azerbaijan", "BAK", "aze", "az"));
            countriesList.add (new Countries_DB ("Bahamas", "NAS", "bhs", "bs"));
            countriesList.add (new Countries_DB ("Bahrain", "BAH", "bhr", "bh"));
            countriesList.add (new Countries_DB ("Bangladesh", "BZL", "bgd", "bd"));
            countriesList.add (new Countries_DB ("Barbados", "BGI", "brb", "bb"));
            countriesList.add (new Countries_DB ("Belarus", "MSQ", "blr", "by"));
            countriesList.add (new Countries_DB ("Belgica", "ANR", "bel", "be"));
            countriesList.add (new Countries_DB ("Belize", "BZE", "blz", "bz"));
            countriesList.add (new Countries_DB ("Benin", "COO", "ben", "bj"));
            countriesList.add (new Countries_DB ("Bhutan", "PBH", "btn", "bt"));
            countriesList.add (new Countries_DB ("Bolivia (Plurinational State of)", "CBB", "bol", "bo"));
            countriesList.add (new Countries_DB ("Bosnia and Herzegovina", "OMO", "bih", "ba"));
            countriesList.add (new Countries_DB ("Botswana", "FRW", "bwa", "bw"));
            countriesList.add (new Countries_DB ("Brasil", "AJU", "bra", "br"));
            countriesList.add (new Countries_DB ("British Virgin Islands", "EIS", "vgb", "vg"));
            countriesList.add (new Countries_DB ("Brunei Darussalam", "BWN", "brn", "bn"));
            countriesList.add (new Countries_DB ("Bulgaria", "BOJ", "bgr", "bg"));
            countriesList.add (new Countries_DB ("Burkina Faso", "BOY", "bfa", "bf"));
            countriesList.add (new Countries_DB ("Burundi", "BJM", "bdi", "bi"));
            countriesList.add (new Countries_DB ("Cabo Verde", "RAI", "cpv", "cv"));
            countriesList.add (new Countries_DB ("Cambodia", "PNH", "khm", "kh"));
            countriesList.add (new Countries_DB ("Cameroon", "DLA", "cmr", "cm"));
            countriesList.add (new Countries_DB ("Canada", "YAT", "can", "ca"));
            countriesList.add (new Countries_DB ("Cayman Islands", "GCM", "cym", "cy"));
            countriesList.add (new Countries_DB ("Central African Republic", "BBY", "caf", "cf"));
            countriesList.add (new Countries_DB ("Chad", "AEH", "tcd", "td"));
            countriesList.add (new Countries_DB ("Chile", "CJC", "chl", "cl"));
            countriesList.add (new Countries_DB ("China", "AAT", "chn", "cn"));
            countriesList.add (new Countries_DB ("Colombia", "BAQ", "col", "co"));
            countriesList.add (new Countries_DB ("Comoros", "AJN", "com", "km"));
            countriesList.add (new Countries_DB ("Congo", "BZV", "cog", "cg"));
            countriesList.add (new Countries_DB ("Cook Island", "RAR", "cok", "ck"));
            countriesList.add (new Countries_DB ("Costa Rica", "SJO", "cri", "cr"));
            countriesList.add (new Countries_DB ("Cote d'Ivoire", "ABJ", "civ", "ci"));
            countriesList.add (new Countries_DB ("Croatia", "DBV", "hrv", "hr"));
            countriesList.add (new Countries_DB ("Cuba", "CFG", "cub", "cu"));
            countriesList.add (new Countries_DB ("Cyprus", "AKT", "cyp", "cy"));
            countriesList.add (new Countries_DB ("Czechia", "PRG", "cze", "cz"));
            countriesList.add (new Countries_DB ("Denmark", "AAR", "dnk", "dk"));
            countriesList.add (new Countries_DB ("Djibouti", "JIB", "dji", "dj"));
            countriesList.add (new Countries_DB ("Dominica", "DOM", "dma", "dm"));
            countriesList.add (new Countries_DB ("Dominican Republic", "LRM", "dom", "do"));
            countriesList.add (new Countries_DB ("Ecuador", "GYE", "ecu", "ec"));
            countriesList.add (new Countries_DB ("Egypt", "AUE", "egy", "eg"));
            countriesList.add (new Countries_DB ("El Salvador", "SAL", "slv", "sv"));
            countriesList.add (new Countries_DB ("Equatorial Guinea", "SSG", "gnq", "gq"));
            countriesList.add (new Countries_DB ("Eritrea", "ASM", "eri", "er"));
            countriesList.add (new Countries_DB ("Estonia", "QUF", "est", "ee"));
            countriesList.add (new Countries_DB ("Ethiopia", "ADD", "eth", "et"));
            countriesList.add (new Countries_DB ("Fiji", "CST", "fji", "fj"));
            countriesList.add (new Countries_DB ("Finland", "ENF", "fin", "fi"));
            countriesList.add (new Countries_DB ("Francia", "AJA", "fra", "fr"));
            countriesList.add (new Countries_DB ("French Polynesia", "BOB", "pyf", "pf"));
            countriesList.add (new Countries_DB ("Gabon", "LBQ", "gab", "ga"));
            countriesList.add (new Countries_DB ("Gambia", "BJL", "gmb", "gm"));
            countriesList.add (new Countries_DB ("Georgia", "TBS", "geo", "ge"));
            countriesList.add (new Countries_DB ("Germany", "AGB", "deu", "de"));
            countriesList.add (new Countries_DB ("Ghana", "ACC", "gha", "gh"));
            countriesList.add (new Countries_DB ("Greece", "GPA", "grc", "gr"));
            countriesList.add (new Countries_DB ("Greenland", "UAK", "grl", "gl"));
            countriesList.add (new Countries_DB ("Grenada", "GND", "grd", "gd"));
            countriesList.add (new Countries_DB ("Guam", "SUM", "gum", "gu"));
            countriesList.add (new Countries_DB ("Guatemala", "GUA", "gtm", "gt"));
            countriesList.add (new Countries_DB ("Guinea", "CKY", "gin", "gn"));
            countriesList.add (new Countries_DB ("Guinea-Bissau", "BXO", "gnb", "gw"));
            countriesList.add (new Countries_DB ("Guyana", "CAY", "guy", "gy"));
            countriesList.add (new Countries_DB ("Haiti", "JAK", "hti", "ht"));
            countriesList.add (new Countries_DB ("Honduras", "JUT", "hnd", "hn"));
            countriesList.add (new Countries_DB ("Hungary", "BUD", "hun", "hu"));
            countriesList.add (new Countries_DB ("Iceland", "EGS", "isl", "is"));
            countriesList.add (new Countries_DB ("India", "AMD", "ind", "in"));
            countriesList.add (new Countries_DB ("Indonesia", "AYW", "idn", "id"));
            countriesList.add (new Countries_DB ("Iran (Islamic Republic of)", "ABD", "irn", "ir"));
            countriesList.add (new Countries_DB ("Iraq", "BGW", "irq", "iq"));
            countriesList.add (new Countries_DB ("Ireland", "ORK", "irl", "ie"));
            countriesList.add (new Countries_DB ("Israel", "ETH", "isr", "il"));
            countriesList.add (new Countries_DB ("Italy", "AHO", "ita", "it"));
            countriesList.add (new Countries_DB ("Jamaica", "KIN", "jam", "jm"));
            countriesList.add (new Countries_DB ("Japan", "AXT", "jpn", "jp"));
            countriesList.add (new Countries_DB ("Jordan", "AMM", "jor", "jo"));
            countriesList.add (new Countries_DB ("Kazakhstan", "ALA", "kaz", "kz"));
            countriesList.add (new Countries_DB ("Kenya", "MYD", "ken", "ke"));
            countriesList.add (new Countries_DB ("Kiribati", "CXI", "kir", "ki"));
            countriesList.add (new Countries_DB ("Korea (Democratic People's Republic of)", "FNJ", "prk", "kp"));
            countriesList.add (new Countries_DB ("Korea, Republic of", "ICN", "kor", "kr"));
            countriesList.add (new Countries_DB ("Kuwait", "KWI", "kwt", "kw"));
            countriesList.add (new Countries_DB ("Kyrgyzstan", "FRU", "kgz", "kg"));
            countriesList.add (new Countries_DB ("Lao People's Democratic Republic", "VTE", "lao", "la"));
            countriesList.add (new Countries_DB ("Latvia", "RIX", "lva", "lv"));
            countriesList.add (new Countries_DB ("Lebanon", "BEY", "lbn", "lb"));
            countriesList.add (new Countries_DB ("Lesotho", "MSU", "lso", "ls"));
            countriesList.add (new Countries_DB ("Liberia", "MLW", "lbr", "lr"));
            countriesList.add (new Countries_DB ("Libya", "BEN", "lby", "ly"));
            countriesList.add (new Countries_DB ("Lithuania", "VNO", "ltu", "lt"));
            countriesList.add (new Countries_DB ("Luxembourg", "LUX", "lux", "lu"));
            countriesList.add (new Countries_DB ("Madagascar", "TNR", "mdg", "mg"));
            countriesList.add (new Countries_DB ("Malawi", "BLZ", "mwi", "mw"));
            countriesList.add (new Countries_DB ("Malaysia", "BTU", "mys", "my"));
            countriesList.add (new Countries_DB ("Mali", "BKO", "mli", "ml"));
            countriesList.add (new Countries_DB ("Malta", "MLA", "mlt", "mt"));
            countriesList.add (new Countries_DB ("Marshall Islands", "UIT", "mhl", "mh"));
            countriesList.add (new Countries_DB ("Mauritania", "NDB", "mrt", "mr"));
            countriesList.add (new Countries_DB ("Mauritius", "MRU", "mus", "mu"));
            countriesList.add (new Countries_DB ("Mexico", "ACA", "mex", "mx"));
            countriesList.add (new Countries_DB ("Mongolia", "ULN", "mng", "mn"));
            countriesList.add (new Countries_DB ("Montenegro", "TGD", "mne", "me"));
            countriesList.add (new Countries_DB ("Morocco", "AGA", "mar", "ma"));
            countriesList.add (new Countries_DB ("Mozambique", "BEW", "moz", "mz"));
            countriesList.add (new Countries_DB ("Myanmar", "MDL", "mmr", "mm"));
            countriesList.add (new Countries_DB ("Namibia", "MPA", "nam", "na"));
            countriesList.add (new Countries_DB ("Nepal", "JKR", "npl", "np"));
            countriesList.add (new Countries_DB ("Netherlands", "AMS", "nld", "nl"));
            countriesList.add (new Countries_DB ("New Caledonia", "ILP", "ncl", "nc"));
            countriesList.add (new Countries_DB ("New Zealand", "AKL", "nzl", "nz"));
            countriesList.add (new Countries_DB ("Nicaragua", "MGA", "nic", "ni"));
            countriesList.add (new Countries_DB ("Niger", "AJY", "ner", "ne"));
            countriesList.add (new Countries_DB ("Nigeria", "ABV", "nga", "ng"));
            countriesList.add (new Countries_DB ("Norway", "AES", "nor", "no"));
            countriesList.add (new Countries_DB ("Oman", "MCT", "omn", "om"));
            countriesList.add (new Countries_DB ("Pakistan", "BHV", "pak", "pk"));
            countriesList.add (new Countries_DB ("Palestinian Territory", "GZA", "pse", "ps"));
            countriesList.add (new Countries_DB ("Panama", "JQE", "pan", "pa"));
            countriesList.add (new Countries_DB ("Papua New Guinea", "AYU", "png", "pg"));
            countriesList.add (new Countries_DB ("Paraguay", "ASU", "pry", "py"));
            countriesList.add (new Countries_DB ("Peru", "IQT", "per", "pe"));
            countriesList.add (new Countries_DB ("Philippines", "CEB", "phl", "ph"));
            countriesList.add (new Countries_DB ("Poland", "GDN", "pol", "pl"));
            countriesList.add (new Countries_DB ("Portugal", "FAO", "prt", "pt"));
            countriesList.add (new Countries_DB ("Puerto Rico", "BQN", "pri", "pr"));
            countriesList.add (new Countries_DB ("Qatar", "DOH", "qat", "qa"));
            countriesList.add (new Countries_DB ("Romania", "BUH", "rou", "ro"));
            countriesList.add (new Countries_DB ("Russian Federation", "AER", "rus", "ru"));
            countriesList.add (new Countries_DB ("Rwanda", "KGL", "rwa", "rw"));
            countriesList.add (new Countries_DB ("Saint Kitts and Nevis", "SKB", "kna", "kn"));
            countriesList.add (new Countries_DB ("Saint Lucia", "SLU", "lca", "lc"));
            countriesList.add (new Countries_DB ("Saint Vincent and the Grenadines", "SVD", "vct", "vc"));
            countriesList.add (new Countries_DB ("Samoa", "APW", "wsm", "ws"));
            countriesList.add (new Countries_DB ("San Vicente y las Granadinas", "CIW", "vct", "vc"));
            countriesList.add (new Countries_DB ("Saudi Arabia", "DMM", "sau", "sa"));
            countriesList.add (new Countries_DB ("Senegal", "DKR", "sen", "sn"));
            countriesList.add (new Countries_DB ("Serbia", "BEG", "srb", "rs"));
            countriesList.add (new Countries_DB ("Seychelles", "SEZ", "syc", "sc"));
            countriesList.add (new Countries_DB ("Sierra Leone", "FNA", "sle", "sl"));
            countriesList.add (new Countries_DB ("Singapore", "SIN", "sgp", "sg"));
            countriesList.add (new Countries_DB ("Siria", "ALP", "syr", "sy"));
            countriesList.add (new Countries_DB ("Slovakia", "BTS", "svk", "sk"));
            countriesList.add (new Countries_DB ("Slovenia", "LJU", "svn", "si"));
            countriesList.add (new Countries_DB ("Solomon Islands", "GSI", "slb", "sb"));
            countriesList.add (new Countries_DB ("Somalia", "MGQ", "som", "so"));
            countriesList.add (new Countries_DB ("South Africa", "AGZ", "zaf", "za"));
            countriesList.add (new Countries_DB ("South Sudan", "JUB", "ssd", "ss"));
            countriesList.add (new Countries_DB ("España", "ALC", "esp", "es"));
            countriesList.add (new Countries_DB ("Sri Lanka", "CMB", "lka", "lk"));
            countriesList.add (new Countries_DB ("Sudan", "KSL", "sdn", "sd"));
            countriesList.add (new Countries_DB ("Suriname", "PBM", "sur", "sr"));
            countriesList.add (new Countries_DB ("Sweden", "GOT", "swe", "se"));
            countriesList.add (new Countries_DB ("Switzerland", "ACH", "che", "ch"));
            countriesList.add (new Countries_DB ("Taiwan", "KHH", "twn", "tw"));
            countriesList.add (new Countries_DB ("Tajikistan", "DYU", "tjk", "tj"));
            countriesList.add (new Countries_DB ("Tanzania", "ARK", "tza", "tz"));
            countriesList.add (new Countries_DB ("Thailand", "DMK", "tha", "th"));
            countriesList.add (new Countries_DB ("Togo", "LFW", "tgo", "tg"));
            countriesList.add (new Countries_DB ("Tonga", "TBU", "ton", "to"));
            countriesList.add (new Countries_DB ("Trinidad and Tobago", "POS", "tto", "tt"));
            countriesList.add (new Countries_DB ("Tunisia", "DJE", "tun", "tn"));
            countriesList.add (new Countries_DB ("Turkey", "ADA", "tur", "tr"));
            countriesList.add (new Countries_DB ("Turkmenistan", "ASB", "tkm", "tm"));
            countriesList.add (new Countries_DB ("Uganda", "EBB", "uga", "ug"));
            countriesList.add (new Countries_DB ("Ukraine", "HRK", "ukr", "ua"));
            countriesList.add (new Countries_DB ("United Arab Emirates", "AUH", "are", "ae"));
            countriesList.add (new Countries_DB ("United Kingdom of Great Britain and Northern Ireland", "ABZ", "gbr", "gb"));
            countriesList.add (new Countries_DB ("United States of America", "ABR", "usa", "us"));
            countriesList.add (new Countries_DB ("Uruguay", "MVD", "ury", "uy"));
            countriesList.add (new Countries_DB ("Uzbekistan", "SKD", "uzb", "uz"));
            countriesList.add (new Countries_DB ("Vanuatu", "VLI", "vut", "vu"));
            countriesList.add (new Countries_DB ("Venezuela", "BLA", "ven", "ve"));
            countriesList.add (new Countries_DB ("Viet Nam", "SGN", "vnm", "vn"));
            countriesList.add (new Countries_DB ("Vietnam", "HAN", "vnm", "vn"));
            countriesList.add (new Countries_DB ("Virgin Islands (U.S.)", "STX", "vir", "vi"));
            countriesList.add (new Countries_DB ("Wallis y Futuna", "FUT", "wlf", "wf"));
            countriesList.add (new Countries_DB ("Yemen", "ADE", "yem", "ye"));
            countriesList.add (new Countries_DB ("Zambia", "CIP", "zmb", "zm"));
            countriesList.add (new Countries_DB ("Zimbabwe", "BFO", "zwe", "zw"));

            countriesView.createTableCountries (activity);

            int count = 0;
            for (Countries_DB Countries_db : countriesList) {
                count++;
                Countries_db.setId (count);
                long countrieId = countriesView.createCountry (Countries_db, activity);
                Log.d ("Countries_class", countrieId + " pais creado con exito");
            }
        }
    }
}
